name: Playwright Tests
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # - name: Update apt 
      #   run: apt-get update && apt-get -y install sudo
      - name: Instal unzip
        run: sudo apt install unzip
      - name: Remove cache 
        run: sudo rm -rf /var/cache/apk/*
      - name: Get allure command line
        run: wget --no-verbose -O /tmp/allure-2.18.1.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.18.1/allure-commandline-2.18.1.tgz
      - name: Running /tmp/allure-2.18.1.tgz
        run: tar -xf /tmp/allure-2.18.1.tgz
      - name: Check Files
        run: ls ./allure-2.18.1
      - name: Remove /tmp
        run: sudo rm -rf /tmp/*
      - name: Running chmod -R +x ./allure-2.18.1/bin
        run: chmod -R +x ./allure-2.18.1/bin
      - name: Set ROOT
        run : ROOT=/app \
              PATH=$PATH:/allure-2.18.1/bin
      - name: Create ROOT
        run: mkdir -p $ROOT
      - name: Check allure java-version
        run: allure --version
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Generate Allure html-report
        run: allure generate allure-results -o allure-report --clean
      - name: Upload allure report to artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30
      - name: Setup Page
        uses: actions/configure-pages@v2
      - name: Upload Page artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: allure-report/
      - name: Deploy to Github Page
        id: deployment
        uses: actions/deploy-pages@v1
