name: Playwright Tests
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      # Install JDK for Allure Installation
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Install Unzip for Allure Installation
      - name: Instal unzip
        run: sudo apt install unzip
      # Download and Install Allure 2.13.1.
      - name: Allure archive download
        run: curl -L https://github.com/allure-framework/allure2/releases/download/2.13.1/allure-commandline-2.13.1.zip -o /tmp/allure.zip
      - name: Unzip archive
        run: unzip /tmp/allure.zip
      - name: Install allure
        run: sudo mv allure-2.13.1 /usr/local/share/allure
      - name: Allure binary symlinking
        run: sudo ln -s /usr/local/share/allure/bin/allure /usr/local/bin/allure
      # Log Allure version
      - name: Check allure java-version
        run: allure --version
      # Install Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # Running Test
      - name: Run Playwright tests
        run: npx playwright test
      # Generate Allure html report base on json report in allure-results folder
      - name: Generate Allure html-report
        run: allure generate allure-results -o allure-report --clean
      # Upload report to artifact
      - name: Upload allure report to artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30
      # # Setup Github page with html artifacts
      # - name: Setup Page
      #   uses: actions/configure-pages@v2
      # - name: Upload Page artifact
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: allure-report/
      # - name: Deploy to Github Page
      #   id: deployment
      #   uses: actions/deploy-pages@v1
